In [6]:
def prime(n):
    if n > 1:
        if  n == 2:
                print(n,"is a prime number")
        for i in range(2,n):
            if (n % i) == 0:
                print(n,"is not a prime number")
                break
            else:
                print(n,"is a prime number")
                break
    else:
         print(n,"is not a prime number")

In [22]:
n = int(input("enter number: "))
prime(n)

enter number: 87
87 is a prime number


In [25]:
def fac_count(a):
    c = 0
    for i in range(1,a+1):
        if a%i == 0:
            c = c+1
    return c

In [36]:
def isprime(a):
    fc = fac_count(a)
    if fc == 2:
        return True
    return False

In [39]:
i = int(input())
if isprime(i):
    print("is prime")
else:
    print("not prime")

4523
is prime


In [56]:
lb = 2
ub = 1000
prim_range(lb,ub)
def prim_range(lb,ub):
    for i in range(lb,ub+1):
        if isprime(i):
            print(i,end = ' ')

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983 991 997 

In [57]:
i = input().split()

python program


In [68]:
list(map(str,input()))

465456456


['4', '6', '5', '4', '5', '6', '4', '5', '6']

In [69]:
def addition(n):
    return n+n

In [70]:
list(map(addition,[12,7,3,45]))

[24, 14, 6, 90]

In [78]:
def power(n):
    return n**n

In [79]:
list(map(power,[1,9,8,4,6,0]))

[1, 387420489, 16777216, 256, 46656, 1]

In [80]:
def sqrt(n):
    return n*n

In [81]:
l = list(map(sqrt,[1,2,3,4,5,6]))
for i in l:
    print(i)

1
4
9
16
25
36


In [82]:
Li = [1,2,'a','b','c',3]
def isDigit(n):
    n = str(n)
    if n.isdigit():
        return True
    return False

list(filter(isDigit,Li))

[1, 2, 3]

In [87]:
Li = [2,3,5,7,9,10]
def isDigit(n):
    n = str(n)
    if n.isprime():
        return True
    return False

list(filter(isprime,Li))

[2, 3, 5, 7]

In [90]:
Li = [2,3,5,7,9,10]
def isDigit(n):
    n = str(n)
    if n.isprime():
        return True
    return False

list(filter(isprime,Li))

[2, 3, 5, 7]

In [92]:
def iseven(n):
    if n%2 ==0:
        return True
    return False
def isodd(n):
    if n%2!=0:
        return True
    return False

In [94]:
Li = [2,3,5,7,9,42,98,6,10]
def isDigit(n):
    n = str(n)
    if n.iseven():
        return True
    return False

list(filter(iseven,Li))

[2, 42, 98, 6, 10]

In [95]:
Li = [2,3,5,7,9,42,98,6,10]
def isDigit(n):
    n = str(n)
    if n.isodd():
        return True
    return False

list(filter(isodd,Li))

[3, 5, 7, 9]

In [1]:
h = lambda x : x%2==0
list(filter(h,[1,2,3,4,5]))

[2, 4]

In [4]:
l = [1,2,3,4,5,6,7,8,9,10]
o = lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [17]:
from random import randint as r
for i in range(1,11):
    print(r(1,25))

25
11
6
22
19
3
3
15
19
12


In [18]:
print([i for i in range(1,11) if i%2==0])

[2, 4, 6, 8, 10]


In [20]:
m1 =[r(1,25) for i in range(1,11)]
m2 =[r(1,25) for i in range(1,11)]
m3 =[r(1,25) for i in range(1,11)]
print(m1)
print(m2)
print(m3)

[6, 23, 4, 5, 22, 10, 21, 10, 25, 4]
[22, 17, 15, 21, 15, 8, 25, 2, 2, 22]
[14, 3, 14, 2, 19, 4, 14, 7, 11, 1]


In [29]:
a1 = list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[14, 20, 9, 13, 18, 9, 23, 6, 13, 13]


In [31]:
a2 = list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)

[14, 14, 11, 9, 18, 7, 20, 6, 12, 9]


In [27]:
list(filter(lambda x:x<10,a2))

[9, 7, 6, 9]

In [36]:
list(filter(lambda x:x<10,list(map(lambda x,y:(x+y)//2,m1,m2))))

[9, 9, 6]

In [40]:
import numpy as np

In [41]:
l =[1,2,3,4,5]
a1 = np.array(l)
print(a1)

[1 2 3 4 5]


In [42]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]]


In [43]:
l3 = [[1,2,3],[4,5,6],[7,8,9]]
a3 = np.array(l3)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [82]:
b = np.arange(20,30).reshape(2,5)
print(b)

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [83]:
b = np.arange(20,26).reshape(2,3)
print(b)

[[20 21 22]
 [23 24 25]]
